name: hangman
description: Dart web implementation of the classic Hangman game.
version: 0.0.3

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  english_words: ^3.1.3

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
